name: CI C++ Std compliance

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '.github/workflows/**'
      - 'conanfile.py'
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - '**CMakeLists.txt'
      - '.github/workflows/**'
      - 'conanfile.py'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp_std: [11, 14, 17, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3-pip cmake ninja-build
          pip3 install conan --break-system-packages
          cmake --version

      - name: Configure
        run: >
          cmake --preset Debug -B build
          -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }}

      - name: Build
        run: cmake --build build -j

      - name: Run transaction_recording
        run: ./build/examples/transaction_recording/transaction_recording
